# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
